language: java
jdk:
  - openjdk7
  - oraclejdk7
  #- oraclejdk8
git:
  submodules: false
before_script:
  - git submodule update
  - cd vitro && git checkout maint-rel-1.6.2 && cd ..
  - cd vivo && git checkout maint-rel-1.6.2 && cd ..